spring.application.name=CineScore Backend
server.port=8080
server.address=localhost

spring.datasource.url=jdbc:postgresql://localhost:5432/cinescore
spring.datasource.username=postgres
spring.datasource.password=1308
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
